

const placeholderOptions = [
  "What's on your mind?",
  "Share something cool...",
  "What's happening today?",
  "Got something to say?",
  "Drop your thoughts here!",
  "Any exciting updates?",
  "Speak your mind!",
  "Post a life update!",
  "What’s your latest thought?",
  "Tell us what you’re thinking.",
  "What made you smile today?",
  "Got a hot take?",
  "Start a conversation...",
  "Vent it out here!",
  "Write what you feel.",
  "Your thoughts matter!",
  "Unleash your creativity!",
  "Feeling inspired?",
  "What's your vibe today?",
  "Heard something interesting?",
  "Post your latest win!",
  "What are you grateful for?",
  "Seen anything funny lately?",
  "Any wild dreams last night?",
  "How’s your day going?",
  "Drop a quote you love!",
  "Express yourself...",
  "Share a random thought!",
  "Any song stuck in your head?",
  "Got something to shout out?",
  "The world is listening!",
  "Just type something fun!",
  "Share your current mood!",
  "Write like no one's watching.",
  "A quick note to self?",
];

export default placeholderOptions;
